name = "CIStanPluto"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CausalInference = "8e462317-f959-576b-b3c1-403f26cec956"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StataDTAFiles = "b8b3a5fb-3772-5a86-9e24-bf4afc28128a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StrFs = "299745a8-1dd2-5813-967e-1153b019bdef"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.10"
CausalInference = "0.8"
DataFrames = "1.3"
DataStructures = "0.18"
Distributions = "0.25"
DrWatson = "2.7"
Graphs = "1.5"
MetaGraphs = "0.7"
NamedArrays = "0.9"
Parameters = "0.12"
StataDTAFiles = "0.2"
StatsBase = "0.33"
StrFs = "0.3"
Tables = "1.6"
julia = "1.7.1"
